### ISSUE TITLE
core issue 

### ISSUE THREAD

**Issue by rowanibrahem** [MohamedGomaa201/ChatApp#2]
ال فايلات جوه الcore مش صح خالص يا محمد ارجع شوف السيشن تاني و عدلهم لو مش عارف غلط  ليه ابقي قول 

و محطتش الفونت الاساسي ف main

**Comment by MohamedGomaa201** [comment]
انا صلحت الفيلات تاني استأذنك تشوفيها كده صح ولا لسه في حاجه مش مظبوطه @rowanibrahem
