### ISSUE TITLE
features issue 

### ISSUE THREAD

**Issue by rowanibrahem** [MohamedGomaa201/ChatApp#3]
احنا قلنا كل feature عبارة عن 2 layers 
presenationn later - data layer 
مفروض تبقي كدا 
![Screenshot 2024-10-08 031714](https://github.com/user-attachments/assets/0bab44e7-ffcd-4cc4-9d81-69f4d8bb22ee)

**Comment by MohamedGomaa201** [comment]
عدلتها استأذنك تشوفيها صح ولا لا @rowanibrahem

**Comment by rowanibrahem** [comment]
> عدلتها استأذنك تشوفيها صح ولا لا @rowanibrahem

مظبوط فيه فايل splash model شيله بس

**Comment by MohamedGomaa201** [comment]
تمام شيلته
